name: build & deploy to gh-pages on push

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: npm install -g gatsby-cli
    
    - name: NODEJS
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: deploy
      run: npm install && npm run deploy
