name: build & deploy to gh-pages on push

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: NODEJS
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
        git config --global user.email "khalilali.j@gmail.com"
        git config --global user.name "Khalil Ali"

    - name: deploy
      run: npm install && npm run deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
        GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
        GATSBY_GDOCS_PDF_ID: ${{ secrets.GATSBY_GDOCS_PDF_ID }}
        CI: true
