name: build & deploy to gh-pages on push

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: NODEJS
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install -g gatsby-cli
    - run: |
        git config --global user.email "khalilali.j@gmail.com"
        git config --global user.name "Khalil Ali"

    - name: deploy
      run: npm install && npm run deploy
